# This is a basic workflow to help you get started with Actions

name: check-linting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build n lint"
  build-n-lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.7.5' # Version range or exact version of a Python version to use, using SemVer's version range syntax
            architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Create Virtual Environment
        run: python -m venv VACHAN_VENV
      
      - name: Use VENV
        run: source VACHAN_VENV/bin/activate
        
      - name: install packages
        run: pip install -r requirements.txt
        
      - name: Run linter
        run: pylint --extension-pkg-whitelist='pydantic' app/*.py

