
name: run-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build n lint"
  build-n-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.7.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
            architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
   
      - name: Create Virtual Environment
        run: python -m venv VACHAN_VENV
      
      - name: Use VENV
        run: source VACHAN_VENV/bin/activate
        
      - name: install packages
        run: python -m pip install --upgrade pip | pip install -r requirements.txt
      
      - name: Set up database
        run: |
          sudo apt-get install postgresql libpq-dev
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE DATABASE vachan;"
          sudo -u postgres psql vachan < /home/runner/work/vachan-api/vachan-api/db/seed_DB.sql
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'secret';"
        
      - name: change Python path
        run: echo "PYTHONPATH=${PWD}/app" >> $GITHUB_ENV
        
      - name: Run tests
        run: |
          mkdir logs
          touch logs/API_logs.log
          cd app 
          python -m pytest

